push:
  branches:
    - staging
    - testing

pr:
  enable_comments: true
  sticky_comment: true
  comment_footer: >
    **This only reflects a subset of all builds from https://ci-prod.riot-os.org.
    Please refer to https://ci.riot-os.org for a complete build for now.**

commit:
  skip_keywords: ["ci_skip", "murdock_skip"]

artifacts:
  - output.txt
  - doc-preview/
