push:
  branches:
    # these two enable potential bors support:
    - staging
    - trying

pr:
  enable_comments: true
  sticky_comment: true

commit:
  skip_keywords: ["ci_skip", "murdock_skip"]

artifacts:
  - output.txt
  - doc-preview/
