sudo: required

language: minimal

services:
  - docker

before_install:
  - docker pull riot/riotbuild

before_script:
  # Fetch the base branch when it is not `master`
  - git fetch origin "${TRAVIS_BRANCH}:${TRAVIS_BRANCH}"

script:
  - docker run -a STDIN -a STDOUT -a STDERR --rm -u "$(id -u)"
      -v "${PWD}:/data/riotbuild" -v /etc/localtime:/etc/localtime:ro
      riot/riotbuild make static-test
