# List of commit statuses that must pass on the PR commit when it is r+-ed.
# (listed in same order as in the repo's branch protection settings)
pr_status = [
 "python-tests",
 "tools-build",
 "check-labels",
 "static-tests",
 "check-commits (commit-msg)",
 "check-commits (pr-check)",
 "Murdock",
 ]

# List of commit statuses that must pass on the merge commit before it is
# pushed to master.
status = [
  "Murdock",
  "static-tests",
  "tools-build",
  ]

# Number of project members who must approve the PR (using GitHub Reviews)
# before it is pushed to master.
# This necessary even with the check-labels action (which checks for >1 ACKs),
# as that passes when there's no review or no special label set.
required_approvals = 1

# delete branch after successful merge
delete_merged_branches = true
