#ifndef NAND_SAMSUNG_TIMING_H
#define NAND_SAMSUNG_TIMING_H

#ifdef __cplusplus
extern "C" {
#endif

#if 0
#define NAND_SAMSUNG_TIMING_NANOSEC(x)              (x)
#endif
#define NAND_SAMSUNG_TIMING_NANOSEC(x)              (0)
#define NAND_SAMSUNG_TIMING_MICROSEC(x)             (NAND_SAMSUNG_TIMING_NANOSEC(1000 * (x)))

#define NAND_SAMSUNG_TIMING_IGNORE                  (0)
#define NAND_SAMSUNG_TIMING_INFINITY                (NAND_SAMSUNG_TIMING_MICROSEC(10000))

#define NAND_SAMSUNG_TIMING_ADL                     (NAND_SAMSUNG_TIMING_NANOSEC(400))
#define NAND_SAMSUNG_TIMING_BERS                    (NAND_SAMSUNG_TIMING_NANOSEC(500))
#define NAND_SAMSUNG_TIMING_CCS                     (NAND_SAMSUNG_TIMING_NANOSEC(500))
#define NAND_SAMSUNG_TIMING_CEH                     (NAND_SAMSUNG_TIMING_NANOSEC(20))
#define NAND_SAMSUNG_TIMING_CH                      (NAND_SAMSUNG_TIMING_NANOSEC(20))
#define NAND_SAMSUNG_TIMING_CS                      (NAND_SAMSUNG_TIMING_NANOSEC(70))
#define NAND_SAMSUNG_TIMING_DH                      (NAND_SAMSUNG_TIMING_NANOSEC(20))
#define NAND_SAMSUNG_TIMING_DS                      (NAND_SAMSUNG_TIMING_NANOSEC(40))
#define NAND_SAMSUNG_TIMING_FEAT                    (NAND_SAMSUNG_TIMING_MICROSEC(1))
#define NAND_SAMSUNG_TIMING_ITC                     (NAND_SAMSUNG_TIMING_MICROSEC(1))
#define NAND_SAMSUNG_TIMING_PROG                    (NAND_SAMSUNG_TIMING_MICROSEC(3))
#define NAND_SAMSUNG_TIMING_R                       (NAND_SAMSUNG_TIMING_MICROSEC(200))
#define NAND_SAMSUNG_TIMING_RR                      (NAND_SAMSUNG_TIMING_NANOSEC(40))
#define NAND_SAMSUNG_TIMING_RST                     (NAND_SAMSUNG_TIMING_MICROSEC(5000))
#define NAND_SAMSUNG_TIMING_WB                      (NAND_SAMSUNG_TIMING_NANOSEC(200))
#define NAND_SAMSUNG_TIMING_WHR                     (NAND_SAMSUNG_TIMING_NANOSEC(120))
#define NAND_SAMSUNG_TIMING_WW                      (NAND_SAMSUNG_TIMING_NANOSEC(100))

#define NAND_SAMSUNG_TIMING_PLEBSY                  (NAND_SAMSUNG_TIMING_BERS)
#define NAND_SAMSUNG_TIMING_PLPBSY                  (NAND_SAMSUNG_TIMING_PROG)
#define NAND_SAMSUNG_TIMING_PLRBSY                  (NAND_SAMSUNG_TIMING_R)
#define NAND_SAMSUNG_TIMING_PCBSY                   (NAND_SAMSUNG_TIMING_PROG)
#define NAND_SAMSUNG_TIMING_RCBSY                   (NAND_SAMSUNG_TIMING_R)

#define NAND_SAMSUNG_TIMING_VDLY                    (NAND_SAMSUNG_TIMING_NANOSEC(50))
#define NAND_SAMSUNG_TIMING_CEVDLY                  (NAND_SAMSUNG_TIMING_NANOSEC(50))
#define NAND_SAMSUNG_TIMING_ENI                     (NAND_SAMSUNG_TIMING_NANOSEC(15))
#define NAND_SAMSUNG_TIMING_ENO                     (NAND_SAMSUNG_TIMING_NANOSEC(50))

#define NAND_SAMSUNG_TIMING_ZQCL                    (NAND_SAMSUNG_TIMING_MICROSEC(1))
#define NAND_SAMSUNG_TIMING_ZQCS                    (NAND_SAMSUNG_TIMING_NANOSEC(400))

#define NAND_SAMSUNG_TIMING_ALH                     (NAND_SAMSUNG_TIMING_NANOSEC(20))
#define NAND_SAMSUNG_TIMING_ALS                     (NAND_SAMSUNG_TIMING_NANOSEC(50))
#define NAND_SAMSUNG_TIMING_AR                      (NAND_SAMSUNG_TIMING_NANOSEC(25))
#define NAND_SAMSUNG_TIMING_CEA                     (NAND_SAMSUNG_TIMING_NANOSEC(100))
#define NAND_SAMSUNG_TIMING_CHZ                     (NAND_SAMSUNG_TIMING_NANOSEC(100))
#define NAND_SAMSUNG_TIMING_CLH                     (NAND_SAMSUNG_TIMING_NANOSEC(20))
#define NAND_SAMSUNG_TIMING_CLR                     (NAND_SAMSUNG_TIMING_NANOSEC(20))
#define NAND_SAMSUNG_TIMING_CLS                     (NAND_SAMSUNG_TIMING_NANOSEC(50))
#define NAND_SAMSUNG_TIMING_COH                     (NAND_SAMSUNG_TIMING_NANOSEC(0))
#define NAND_SAMSUNG_TIMING_CR                      (NAND_SAMSUNG_TIMING_NANOSEC(10))
#define NAND_SAMSUNG_TIMING_CR2                     (NAND_SAMSUNG_TIMING_NANOSEC(100))
#define NAND_SAMSUNG_TIMING_CR2_READ_ID             (NAND_SAMSUNG_TIMING_NANOSEC(150))
#define NAND_SAMSUNG_TIMING_CS3                     (NAND_SAMSUNG_TIMING_NANOSEC(100))
#define NAND_SAMSUNG_TIMING_IR                      (NAND_SAMSUNG_TIMING_NANOSEC(10))
#define NAND_SAMSUNG_TIMING_RC                      (NAND_SAMSUNG_TIMING_NANOSEC(100))
#define NAND_SAMSUNG_TIMING_REA                     (NAND_SAMSUNG_TIMING_NANOSEC(40))
#define NAND_SAMSUNG_TIMING_REH                     (NAND_SAMSUNG_TIMING_NANOSEC(30))
#define NAND_SAMSUNG_TIMING_RHOH                    (NAND_SAMSUNG_TIMING_NANOSEC(0))
#define NAND_SAMSUNG_TIMING_RHW                     (NAND_SAMSUNG_TIMING_NANOSEC(200))
#define NAND_SAMSUNG_TIMING_RHZ                     (NAND_SAMSUNG_TIMING_NANOSEC(200))
#define NAND_SAMSUNG_TIMING_RLOH                    (NAND_SAMSUNG_TIMING_NANOSEC(0))
#define NAND_SAMSUNG_TIMING_RP                      (NAND_SAMSUNG_TIMING_NANOSEC(50))
#define NAND_SAMSUNG_TIMING_WC                      (NAND_SAMSUNG_TIMING_NANOSEC(100))
#define NAND_SAMSUNG_TIMING_WH                      (NAND_SAMSUNG_TIMING_NANOSEC(30))
#define NAND_SAMSUNG_TIMING_WP                      (NAND_SAMSUNG_TIMING_NANOSEC(50))

#ifdef __cplusplus
}
#endif

#endif /* NAND_SAMSUNG_TIMING_H */